### ISSUE TITLE
Add ControlMode on AccessPoints

### ISSUE THREAD

**Issue by Maxhy** [islog/leosac#10]
Current implementation only supports one control mode: it opens few seconds a door if the AuthRequest is authorized. Abstraction level should be added and end-user should be able to configure a list of control mode according to days / hours / . For instance:
 * Always Open
 * Always Close
 * Default AuthRequests behavior
 * Keep Open on first AuthRequest success, Close on second.
 * ...

**Comment by xaqq** [comment]
We could implement this in the doorman module.

It would require an additional configuration file to store schedule and door's state/profile.

**Comment by xaqq** [comment]
The doorman module configuration has been extended. It is now possible to define doors and schedules were their states cannot be changed (aka always open/closed).

For opening on first access, and closing on second this is possible through proper configuration of the action in response to a successful authentication. Sending the `TOGGLE` command to the door is the way to go.
