### ISSUE TITLE
Create an advanced Authentication module

### ISSUE THREAD

**Issue by Maxhy** [islog/leosac#11]
Current Authentication module is too simple. A new auth module should be created with support of the following features:
 * Users: firstname, lastname, email, enabled, optional groups, optional schedules, optional validity start, optional validity end
 * Groups: name, optional schedules
 * Schedules: name, days, hours
 * Cards: name, cardid, enabled, user, optional schedules, optional validity start, optional validity end

We should also support holidays and 3*8 organization.

**Comment by xaqq** [comment]
The auth-file module has been patched to support those requirements except for holidays and 3x8 which will eventually be implemented later.
