### ISSUE TITLE
sysfsgpio ON with timer

### ISSUE THREAD

**Issue by xaqq** [islog/leosac#48]
The `ON` command with a timer is not implemented in `sysfsgpio` and will simply ignore the timer silently.

**Comment by twaymouth** [comment]
Hi, Just wondering if there has been any progress with this issue? I have leosac working with a Raspberry Pi and Weigand reader, however when the door is "unlocked" as above the timer value appears to be ignored and the door never locks after the time period.

**Comment by xaqq** [comment]
Hello,
Yes this issue should now be fixed in version 0.6.1. 

Can you let me know if upgrading to 0.6.1 solves the problem for you.

**Comment by twaymouth** [comment]
Much appreciated, From the code changes I can see under the modules source it looks like it should be fixed. I will compile it and let you know how it goes.

**Comment by xaqq** [comment]
You can install the debian package if you prefer.

**Comment by twaymouth** [comment]
Working like a charm, thanks. Only thing to note is that I had to add the "Jessie" Repositories to my sources list before the debian package would install. Might be worth updating the install instructions to include this as it had going in circles for a while. 

"deb http://archive.raspbian.org/raspbian jessie main"

Thanks for your help.

**Comment by xaqq** [comment]
Thank you for feedback. I did update the release notes.
