### ISSUE TITLE
libsysfsgpio.so not setting gpio name

### ISSUE THREAD

**Issue by tagno25** [islog/leosac#63]
I am trying to use libsysfsgpio.so to talk to my wiegand reader, but both libled-buzzer.so and libwiegand.so are complaining about GPIOs not existing.  I can see that they are being exported correctly, but later modules are not able to use them.

using Leosac from leosac_0.6.0-1_armhf.deb on a Raspberry Pi B+

Config: http://pastebin.com/dad7w8HR
Log: http://pastebin.com/0A0KKJ2U

**Comment by tagno25** [comment]
errors fixed with pull #64 

Still have to test I/O on hardware

**Comment by xaqq** [comment]
Thank you for the patch. BTW be wary of #48 when playing around with libsysfsgpio.
