### ISSUE TITLE
WS-Notifier Module not working for HTTPS URLs

### ISSUE THREAD

**Issue by Marcus-L** [islog/leosac#69]
Module: libwsnotifier.so, using <url> with https://

From the log, getting an error message with every notification attempt:
[2016-01-04 16:40:02.249] [console] [warning] curl_easy_perform() failed: Out of memory

Relevant code:
https://github.com/islog/leosac/blob/develop/src/modules/ws-notifier/WebServiceNotifier.cpp

Possible solution:
http://stackoverflow.com/questions/166617/curle-out-of-memory-error-when-posting-via-https

"add the flag CURL_GLOBAL_SSL to curl_global_init"

**Comment by xaqq** [comment]
Hello,

Thank you for the report. Your possible solution is indeed correct.
However to work with self-signed cert (which I used to reproduce the issue) a bit more work is needed -- mostly providing additional configuration option to prevent certificate validation.

I have a patch mostly ready that I will probably push tomorrow.

**Comment by Marcus-L** [comment]
Thanks so much for the quick update!

On Fri, Jan 8, 2016 at 9:44 AM, KAPP Arnaud <notifications@github.com>
wrote:

> Closed #69 <https://github.com/islog/leosac/issues/69> via 975000a
> <https://github.com/islog/leosac/commit/975000a1a5f4cb96dd97604b7dc6b92deab76db2>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/islog/leosac/issues/69#event-509472320>.
>



-- 
-Marcus
